### ISSUE TITLE
error 500 on craft CMS dashboard after adding widget 

### ISSUE THREAD

**Issue by jjacinto0** [dispositiontools/craft-alt-text-generator#1]
I encountered error 500 on Craft CMS dashboard after I added the widget (Image Alt Text Stats widget) but I can access other settings.

Here is the versions
Craft CMS: Pro 4.5.9
Alt text Generator: 1.0.2
Multisite: yes

**Comment by dispositiontools** [comment]
I'm very sorry - I'll get this fixed today

**Comment by dispositiontools** [comment]
Hi @jjacinto0 
I've pushed an update that catches a couple of issues when there is an issue with the API call, whether it is a connection issue, an issue with the API key, or no API key set. 
but, I'm not completely sure if that is the error you were encountering. Could your this update for me to see if it fixes your issue? If it doesn't then would you be able to turn dev mode on so I can see more details of the error?

I'm really sorry you had this issue.

**Comment by dispositiontools** [comment]
@jjacinto0 When you get a moment can you the update to see if that fixed it for you?

**Comment by dispositiontools** [comment]
Hi @jjacinto0 I'm going to close this issue now - but please do get back in contact if the issue persists or if you have any other issues.
