### ISSUE TITLE
increase the max image processing size to 16Mb

### ISSUE THREAD

**Issue by MattAppleton** [dispositiontools/craft-alt-text-generator#10]
It is now possible to process up to 16Mb images via alt text.ai — as of today according to Dave at their support!

If its possible to update the plugin to reflect this new overhead it would be super useful for one of my client sites in particular :)

thanks

**Comment by dispositiontools** [comment]
Hi @MattAppleton 

Yes! I'll make that update this weekend. Sorry for the delay, I've been away. 
I'm also adding the ability to use craft transforms to then be able to send even larger images (but as a config setting so it's optional)

**Comment by dispositiontools** [comment]
Hi @MattAppleton 

I've pushed the update for the Craft 4 version (v4.2.0) to increase to the new limit, and also added the option of Craft transforming too large images. 
 will be pushing the Craft 5 version soon,

**Comment by MattAppleton** [comment]
Great — very keen to get the C5 version going :)

**Comment by dispositiontools** [comment]
C5 version has now been pushed with v5.2.0 - I just needed that extra time to test on C5 with a couple of servers

**Comment by MattAppleton** [comment]
Great! Gonna try that now...

**Comment by dispositiontools** [comment]
let me know any feed back. i've got some improvements coming for the listing pages to make that faster and give quick links to the asset as well

**Comment by MattAppleton** [comment]
5.2.0 doesn't show up yet in the plugin store, is there another way I can pull it?

**Comment by dispositiontools** [comment]
you can change your composer.json to update the version for alt-text-generator to 5.2.0
ie 
"dispositiontools/craft-alt-text-generator": "^5.2.0",
and composer update 
that should bring it in for you

**Comment by MattAppleton** [comment]
First question is... how to get the plugin to 'recrawl / recheck' my images?

Theres a bunch that were too big for the plugin to process last time round ...

Can I do this via Command line? I can't use the history / errors yet... ! 

Thanks for looking!

**Comment by dispositiontools** [comment]
You can use the utility for that, 
screenshot: https://d.pr/i/wq05h8

and click resubmit to send all the images back to alttext.ai

**Comment by dispositiontools** [comment]
@MattAppleton i'm heading to bed. Leave me any notes / questions / issue you have and I'll pick it up in the morning. Thanks for taking a look

**Comment by MattAppleton** [comment]
@dispositiontools  — sorry, forgot to look in the utilities section. Running that now, thanks very much.

**Comment by MattAppleton** [comment]
All working well now on C4 + C5 — thanks... I have one other but of feedback, will post...

**Comment by dispositiontools** [comment]
Thanks @MattAppleton
