### ISSUE TITLE
Error Argument #2 ($array) must be of type array, null given

### ISSUE THREAD

**Issue by markus-antoni** [dispositiontools/craft-alt-text-generator#2]
Hi,

I got error "array_key_exists(): Argument #2 ($array) must be of type array, null given".
Also added credits to alttext.ai - same issue.

![2023-11-09_20-33-55](https://github.com/dispositiontools/craft-alt-text-generator/assets/11946330/20ab38af-1ffd-4564-9745-3df6b406b14c)

It is a fairly new craft installation (4.5.10.) without any specials.

Any ideas?

Best,
Markus

**Comment by dispositiontools** [comment]
Thank you for letting me know. I'm going to take a look now.

**Comment by dispositiontools** [comment]
Hi @markus-antoni  thank you for bringing this to my attention. I've pushed v1.0.4 that fixes this error. I was missing the instance when someone had an account and was in pay in as you go mode, or when they were in a free trial. I've update the code to correctly allow for this.

**Comment by markus-antoni** [comment]
THX for fast fixing!

**Comment by dispositiontools** [comment]
@markus-antoni I returned your email via my helpdesk software - sorry to botheryou - but could you let me know if you got it? Just wanted to make sure it arrived.
