### ISSUE TITLE
AWS asset url issue

### ISSUE THREAD

**Issue by john-henry** [dispositiontools/craft-alt-text-generator#4]
Hi there,

Craft 5.1.0

There is an issue when using AWS as an asset location. 

https://github.com/dispositiontools/craft-alt-text-generator/blob/main/src/services/AltTextAiApi.php#L680

` $imageUrl = UrlHelper::siteUrl($assetUrl);`

> craft\helpers\UrlHelper::siteUrl(): Argument #1 ($path) must be of type string, null given, called in /var/www/html/vendor/dispositiontools/craft-alt-text-generator/src/services/AltTextAiApi.php on line 680

**Comment by john-henry** [comment]
An update. I think the plugin may not work for me as I use Cloudfront for my image's transforms which means there is no public URL for s3

**Comment by dispositiontools** [comment]
hi @john-henry oooo thats interesting - can you give me a few of days to come back with you with some thing to test - I've been looking at giving an option of sending alttext.ai a transformed image - which might work for this option. 
it will also give the possiblity of sending other images to aittext.ai like svgs and avif which alttext.ai currently doesn't accept. 
I'm looking to have something to test next weekend.

**Comment by john-henry** [comment]
Thanks. yeah, I was experimenting with the following, which would also solve sending over large files vai the API

`$assetUrl = Craft::$app->getAssets()->getImagePreviewUrl($asset, 1000, 1000);`

**Comment by dispositiontools** [comment]
@john-henry Thank you for this, I've implemented this on the Craft 4 version (v4.2.0) and am just working to push it for the Craft 5 version, and then will implement it for svg and avif. I forgot to credit you in the update notice for v4.2.0 and I will do in the next push. Thank you
