### ISSUE TITLE
Use with a translatable field

### ISSUE THREAD

**Issue by mathg** [dispositiontools/craft-alt-text-generator#7]
Hi! Thanks for the module it's great! We consider using this on our website but since it's a multilingual website we have to use another field for Alt text that we make translatable. Is it something that would be possible with this module? A feature that is planned to be built in the future?

Thanks

**Comment by dispositiontools** [comment]
Hi @mathg 

Yes, this is in active development at the moment with 2 aspects. 

1. allowing using a custom field rather than Crafts built in field, 
2. There is an issue with the alttext.ai api which means that you can't request multiple languages in one call, I've contacted them and they are considering changing that. 
3. In the meantime I'm looking at resubmitting the image to alttext.ai for each language - but this does use up credits faster. 


The use of custom fields should be out in the 7 days or so

**Comment by mathg** [comment]
Cool thanks for the quick response!

**Comment by mathg** [comment]
Hello, sorry to ask about this update, but is this something that is still close to a release? We would definitely like to implement it on our website. Thank you very much for your time on this plugin!

**Comment by bfopma** [comment]
Seconding @mathg's request, above. We have an existing site that is using a custom field for alt text (Craft did not have the native alt text field when this site was originally built). Can you please provide an update on whether using a custom field is possible?

**Comment by dispositiontools** [comment]
I'll be adding this this weekend along with a few other improvements

**Comment by dispositiontools** [comment]
@mathg @bfopma  I've push this now for the Craft 4 version (v4.2.0) and just working to push it for the Craft 5 version.

**Comment by dispositiontools** [comment]
This has now been pushed for the Craft 5 version (v5.20)

**Comment by mathg** [comment]
@dispositiontools I tried updating the plugin to use the new custom field, the issue is there is no way to set the proper language with the image beside the one that has been set in the settings. One idea could be to use the siteId to define the language to query the api with. I see that you already have the siteId column in your database

**Comment by dispositiontools** [comment]
hi @mathg thats helpful - what version of Craft are you using with it?

**Comment by mathg** [comment]
Craft 4.x 

I have made some changes locally to make it work using that siteId. I can create a PR so you can see how I managed and if it fully works. So far it works for me.

**Comment by dispositiontools** [comment]
yes please! that is kind of you

**Comment by mathg** [comment]
@dispositiontools I don't know if you had time to look at it, but I made a PR including some changes I've made on my end to allow this. I know there is some formatting changes in the PR though, anyway this could be a way to handle this issue.
