### ISSUE TITLE
Add .env API key support

### ISSUE THREAD

**Issue by svondervoort** [dispositiontools/craft-alt-text-generator#8]
It would be great to be able to set the Alttext.ai API key via the .env file instead of in the config/settings.

**Comment by dispositiontools** [comment]
@svondervoort on the list for this weekend - sorry for the delay

**Comment by svondervoort** [comment]
Thats great news, no hurry. Its just a nice to have feature.

**Comment by dispositiontools** [comment]
@svondervoort I've pushed this for the Craft 4 vesion (v4.2.0) and just working it through for the Craft 5 version. Thanks for the idea.
